### PR TITLE
Remove all history manipulation

### PR DESCRIPTION
**Pull request by gaelicWizard**
Remove mangling of HISTCONTROL and remove use of history as a mechanism for detecting the "current" command. Instead, use $BASH_COMMAND like Jesus intended.

### CODE REVIEW

**Comment by dimo414** [comment]
Can you detail what, if any, behavior differences users will observe with this change? I assume this would be a breaking change?

**Comment by rcaloras** [comment]
@gaelicWizard thanks for the initiative with the PR and @dimo414 thanks for chiming in. 

My sentiment on this change is the same as mentioned prior in: https://github.com/rcaloras/bash-preexec/issues/115#issuecomment-779395772 I don't believe the regression of not capturing multiple commands is an acceptable one and favor the trade off here with overriding history to get the command line as its typed. 

With that said, @gaelicWizard if you don't require $1 on preexec, feel free to to remove the history manipulation as mentioned https://github.com/rcaloras/bash-preexec/issues/48#issuecomment-315352858.

If there's another way to get access to the command exactly as it's typed without history in Bash I'd love to update this!

**Comment by gaelicWizard** [comment]
Sorry, this PR is marked draft because I both haven't committed everything nor put in any explanation.

After reading other open issues and PRs, I'm going to actually try to just make the history manipulation conditional rather than remove it. It's now clear to me that it's necessary for a particular use case given constraints.

My motivation is twofold: (1) don't change things behind my back; (2) allow hook to run before each command, rather than before each command _line_.

**Comment by dimo414** [comment]
>  allow hook to run before each command, rather than before each command line.

That's totally reasonable to want, but it's not how bash-preexec is implemented (by design). Are you sure you even want to use bash-preexec? Maybe you just want to implement your own DEBUG trap?

**Comment by gaelicWizard** [comment]
Lol, I can't use bash-preexec *and* a custom debug trap unless I write a wrapper with conditional behavior and...that's why we use bash-preexec: so we get the benefit of each other's improvements.

I'm not the first one to want to be able to use debug hooks along with bash-preexec.

**Comment by gaelicWizard** [comment]
Alsö, #109 would run the preexec hook multiple times on purpose.

**Comment by gaelicWizard** [comment]
I'm closing this PR and will open a whole new one based on #109, which does 98% of what I need. It requires Bash version 5 or higher, but @cornfeedhobo made a comment that makes it not need v5 so I'm just doing that.

**Pull request closed without merging**
